spring.application.name=JavaSprint5_2LibrarySystem
server.port=8080

# ???? local??????? h2???????
spring.profiles.active=local

# Swagger & JSON ???
springdoc.swagger-ui.path=/library/swagger-ui.html
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
