# --- MySQL Configuration (Primary) ---
# Main data: Users, Admins, Books
spring.datasource.url=jdbc:mysql://localhost:3306/library_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=888888
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- MongoDB Configuration (Secondary) ---
# Action logs: Borrow and Return history
spring.data.mongodb.uri=mongodb://localhost:27017/library_history_db
spring.data.mongodb.connect-timeout=3000

# --- Spring Security ---
# Temporary: check th
# e console for the generated password on startup